import type { Principal } from '@dfinity/principal';
export interface BBS {
  'userid' : string,
  'post' : string,
  'timestamp' : bigint,
}
export interface Calendar {
  'id' : bigint,
  'url' : string,
  'status' : bigint,
  'owner' : string,
  'name' : string,
  'description' : string,
  'ispublic' : boolean,
  'isverified' : boolean,
}
export interface Comment {
  'attachid' : bigint,
  'user' : string,
  'comment' : string,
  'timestamp' : bigint,
  'attachtype' : bigint,
}
export interface Event {
  'id' : bigint,
  'tz' : string,
  'end' : bigint,
  'status' : bigint,
  'title' : string,
  'owner' : string,
  'description' : string,
  'calendar' : bigint,
  'start' : bigint,
  'ispublic' : boolean,
  'location' : string,
}
export interface Profile {
  'status' : bigint,
  'subcals' : Array<bigint>,
  'userid' : string,
  'name' : string,
  'role' : bigint,
}
export interface Todo {
  'id' : bigint,
  'status' : bigint,
  'owner' : string,
  'todo' : string,
  'description' : string,
  'duedate' : bigint,
  'calendar' : bigint,
  'ispublic' : boolean,
  'parent' : bigint,
}
export interface Vansday {
  'addCalendar' : (
      arg_0: string,
      arg_1: string,
      arg_2: string,
      arg_3: string,
      arg_4: boolean,
    ) => Promise<undefined>,
  'addComment' : (
      arg_0: string,
      arg_1: bigint,
      arg_2: string,
      arg_3: bigint,
      arg_4: bigint,
    ) => Promise<undefined>,
  'addEvent' : (
      arg_0: bigint,
      arg_1: string,
      arg_2: string,
      arg_3: bigint,
      arg_4: bigint,
      arg_5: string,
      arg_6: string,
      arg_7: string,
      arg_8: boolean,
    ) => Promise<undefined>,
  'addTodo' : (
      arg_0: string,
      arg_1: string,
      arg_2: string,
      arg_3: boolean,
      arg_4: bigint,
    ) => Promise<undefined>,
  'addUser' : (arg_0: string) => Promise<undefined>,
  'completeTodo' : (arg_0: bigint) => Promise<undefined>,
  'editTodo' : (
      arg_0: bigint,
      arg_1: string,
      arg_2: string,
      arg_3: boolean,
      arg_4: bigint,
    ) => Promise<undefined>,
  'getCalEvents' : (arg_0: bigint) => Promise<Array<Event>>,
  'getCalendars' : () => Promise<Array<Calendar>>,
  'getComments' : (arg_0: bigint, arg_1: bigint) => Promise<Array<Comment>>,
  'getEvents' : (arg_0: bigint, arg_1: bigint) => Promise<Array<Event>>,
  'getMyCalendars' : (arg_0: string) => Promise<Array<Calendar>>,
  'getMyEvents' : (arg_0: string, arg_1: bigint, arg_2: bigint) => Promise<
      Array<Event>
    >,
  'getMyTodos' : (arg_0: string) => Promise<Array<Todo>>,
  'getPosts' : () => Promise<Array<BBS>>,
  'getTodos' : () => Promise<Array<Todo>>,
  'idQuick' : () => Promise<Principal>,
  'installer' : () => Promise<Principal>,
  'listUsers' : () => Promise<Array<Profile>>,
  'lookupUser' : (arg_0: string) => Promise<[] | [Profile]>,
  'updateCalendar' : (
      arg_0: bigint,
      arg_1: string,
      arg_2: string,
      arg_3: string,
      arg_4: string,
      arg_5: boolean,
      arg_6: boolean,
      arg_7: bigint,
    ) => Promise<undefined>,
  'updateEvent' : (
      arg_0: bigint,
      arg_1: bigint,
      arg_2: string,
      arg_3: string,
      arg_4: bigint,
      arg_5: bigint,
      arg_6: string,
      arg_7: string,
      arg_8: string,
      arg_9: boolean,
      arg_10: bigint,
    ) => Promise<undefined>,
  'userCount' : () => Promise<bigint>,
  'whoami' : () => Promise<Principal>,
}
export interface _SERVICE extends Vansday {}
